export const CITIES = [
    "Chișinău",
    "Bălți",
    "Tiraspol",
    "Cahul",
    "Ungheni",
    "Soroca",
    "Orhei",
    "Comrat",
    "Strășeni",
    "Edineț",
    "Căușeni",
    "Fălești",
    "Hîncești",
    "Ialoveni",
    "Drochia",
    "Sîngerei",
    "Florești",
    "Rezina",
    "Taraclia",
    "Cimișlia",
    "Nisporeni",
    "Basarabeasca",
    "Cantemir",
    "Glodeni",
    "Leova",
    "Rîșcani",
    "Ștefan Vodă",
    "Telenești",
    "Online"
] as const;

export const THERAPIST_SPECIALIZATIONS = [
    "Psiholog Clinician",
    "Psihoterapeut",
    "Consilier Psihologic",
    "Psihiatru",
    "Logoped",
    "Coach",
    "Psihopedagog",
    "Analist Comportamental"
] as const;

export const THERAPIST_SPECIALTIES = [
    "Anxietate",
    "Depresie",
    "Traumă",
    "Relații de Cuplu",
    "Dezvoltare Personală",
    "Tulburări Alimentare",
    "Adicții",
    "Stres",
    "Burnout",
    "Doliu și Pierdere",
    "Stima de Sine",
    "Managementul Furiei",
    "Tulburări de Somn",
    "Probleme de Familie",
    "Parenting",
    "Tulburări Obsesiv-Compulsive",
    "Fobii",
    "Atacuri de Panică",
    "Tulburări de Personalitate",
    "Dificultăți de Învățare",
    "Autism",
    "ADHD",
    "Probleme Sexuale",
    "Divorț și Separare",
    "Singurătate"
] as const;

export const OFFER_CATEGORIES = [
    "Masaj",
    "Relaxare",
    "Terapie",
    "Yoga",
    "Mindfulness",
    "Detox",
    "Spa",
    "Workshop",
    "Retreat",
    "Evenimente",
    "Cursuri"
] as const;

export const THERAPIST_APPROACHES = [
    "Terapie Cognitiv-Comportamentală (CBT)",
    "Psihanaliză",
    "Terapie Psihodinamică",
    "Terapie Umanistă",
    "Terapie Integrativă",
    "Terapie Sistemică",
    "Gestalt Terapie",
    "Art Terapie",
    "Terapie Centrată pe Emoții (EFT)",
    "Terapie de Familie",
    "Terapie prin Joc (Play Therapy)",
    "Terapie de Schemă",
    "Terapie Narativă",
    "Terapie Centrată pe Client",
    "Analiză Tranzacțională",
    "Hipnoterapie",
    "Terapie Somatică",
    "Mindfulness",
    "EMDR",
    "Terapie de Cuplu"
] as const;
